In [39]:
import pandas as pd
import time
import numpy as np

# Feb 30 days

In [2]:
Feb = pd.read_csv('Feb_tran_id_expire.csv',index_col=['msno'])

In [124]:
size=4e7 # 40 million
reader = pd.read_csv('user_logs.csv',chunksize=size,index_col=['msno'])
start_time = time.time()
for i in range(10):
    user_log_chunk=next(reader)
    
    
    user_log_chunk = user_log_chunk[(user_log_chunk.date<20170301)&(user_log_chunk.date>=20170101)]
    merged = pd.merge(user_log_chunk, Feb,left_index=True,right_index=True, how='inner')
    merged['date'] = pd.to_datetime(merged['date'].astype(str), format='%Y%m%d')
    merged['membership_expire_date'] = pd.to_datetime(merged['membership_expire_date'].astype(str), format='%Y%m%d')
    merged = merged[(merged['membership_expire_date'] > merged['date']) & 
      (merged['membership_expire_date'] <= pd.Timedelta(30, unit='D')+merged['date'])]
    
    if(i==0):
        result=merged
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
    else:
        result=result.append(merged)
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
        
    del(user_log_chunk)
    del(merged)

Loop  0 took 67.71282887458801 seconds
Loop  1 took 126.29947900772095 seconds
Loop  2 took 185.61018300056458 seconds
Loop  3 took 245.4592788219452 seconds
Loop  4 took 306.4285271167755 seconds
Loop  5 took 373.1882300376892 seconds
Loop  6 took 436.9935529232025 seconds
Loop  7 took 508.42966198921204 seconds
Loop  8 took 578.135584115982 seconds
Loop  9 took 631.9289321899414 seconds

In [127]:
result.to_csv("Feb_user_log.csv")

# Jan  30 days

In [3]:
Jan = pd.read_csv('Jan_tran_id_expire.csv',index_col=['msno'])

In [4]:
size=4e7 # 40 million
reader = pd.read_csv('user_logs.csv',chunksize=size,index_col=['msno'])
start_time = time.time()
for i in range(10):
    user_log_chunk=next(reader)
    
    
    user_log_chunk = user_log_chunk[(user_log_chunk.date<20170201)&(user_log_chunk.date>=20161201)]
    merged = pd.merge(user_log_chunk, Jan,left_index=True,right_index=True, how='inner')
    merged['date'] = pd.to_datetime(merged['date'].astype(str), format='%Y%m%d')
    merged['membership_expire_date'] = pd.to_datetime(merged['membership_expire_date'].astype(str), format='%Y%m%d')
    merged = merged[(merged['membership_expire_date'] > merged['date']) & 
      (merged['membership_expire_date'] <= pd.Timedelta(30, unit='D')+merged['date'])]
    
    if(i==0):
        result=merged
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
    else:
        result=result.append(merged)
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
        
    del(user_log_chunk)
    del(merged)

Loop  0 took 55.98421096801758 seconds
Loop  1 took 111.93934988975525 seconds
Loop  2 took 166.89938306808472 seconds
Loop  3 took 226.79107093811035 seconds
Loop  4 took 285.85037183761597 seconds
Loop  5 took 344.13249588012695 seconds
Loop  6 took 403.5533199310303 seconds
Loop  7 took 465.28292202949524 seconds
Loop  8 took 528.0598001480103 seconds
Loop  9 took 576.8208010196686 seconds

In [5]:
result.to_csv("Jan_user_log.csv ")

# Feb 7 days

In [8]:
size=4e7 # 40 million
reader = pd.read_csv('user_logs.csv',chunksize=size,index_col=['msno'])
start_time = time.time()
for i in range(10):
    user_log_chunk=next(reader)
    
    
    user_log_chunk = user_log_chunk[(user_log_chunk.date<20170301)&(user_log_chunk.date>=20170101)]
    merged = pd.merge(user_log_chunk, Feb,left_index=True,right_index=True, how='inner')
    merged['date'] = pd.to_datetime(merged['date'].astype(str), format='%Y%m%d')
    merged['membership_expire_date'] = pd.to_datetime(merged['membership_expire_date'].astype(str), format='%Y%m%d')
    merged = merged[(merged['membership_expire_date'] > merged['date']) & 
      (merged['membership_expire_date'] <= pd.Timedelta(7, unit='D')+merged['date'])]
    
    if(i==0):
        result=merged
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
    else:
        result=result.append(merged)
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
        
    del(user_log_chunk)
    del(merged)

Loop  0 took 62.83083534240723 seconds
Loop  1 took 120.98006010055542 seconds
Loop  2 took 177.7629702091217 seconds
Loop  3 took 236.29664015769958 seconds
Loop  4 took 294.5286719799042 seconds
Loop  5 took 353.4720242023468 seconds
Loop  6 took 413.3743243217468 seconds
Loop  7 took 472.33542919158936 seconds
Loop  8 took 530.9871380329132 seconds
Loop  9 took 579.4899201393127 seconds

In [9]:
result.to_csv("Feb_user_log_7.csv")

# Jan 7 days

In [10]:
size=4e7 # 40 million
reader = pd.read_csv('user_logs.csv',chunksize=size,index_col=['msno'])
start_time = time.time()
for i in range(10):
    user_log_chunk=next(reader)
    
    
    user_log_chunk = user_log_chunk[(user_log_chunk.date<20170201)&(user_log_chunk.date>=20161201)]
    merged = pd.merge(user_log_chunk, Jan,left_index=True,right_index=True, how='inner')
    merged['date'] = pd.to_datetime(merged['date'].astype(str), format='%Y%m%d')
    merged['membership_expire_date'] = pd.to_datetime(merged['membership_expire_date'].astype(str), format='%Y%m%d')
    merged = merged[(merged['membership_expire_date'] > merged['date']) & 
      (merged['membership_expire_date'] <= pd.Timedelta(7, unit='D')+merged['date'])]
    
    if(i==0):
        result=merged
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
    else:
        result=result.append(merged)
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
        
    del(user_log_chunk)
    del(merged)

Loop  0 took 59.162752866744995 seconds
Loop  1 took 119.240886926651 seconds
Loop  2 took 177.97886180877686 seconds
Loop  3 took 238.02198886871338 seconds
Loop  4 took 299.13370180130005 seconds
Loop  5 took 357.82258677482605 seconds
Loop  6 took 417.04016280174255 seconds
Loop  7 took 475.6121699810028 seconds
Loop  8 took 536.3142409324646 seconds
Loop  9 took 583.523827791214 seconds

In [11]:
result.to_csv("Jan_user_log_7.csv")

# Feb 14 days

In [12]:
size=4e7 # 40 million
reader = pd.read_csv('user_logs.csv',chunksize=size,index_col=['msno'])
start_time = time.time()
for i in range(10):
    user_log_chunk=next(reader)
    
    
    user_log_chunk = user_log_chunk[(user_log_chunk.date<20170301)&(user_log_chunk.date>=20170101)]
    merged = pd.merge(user_log_chunk, Feb,left_index=True,right_index=True, how='inner')
    merged['date'] = pd.to_datetime(merged['date'].astype(str), format='%Y%m%d')
    merged['membership_expire_date'] = pd.to_datetime(merged['membership_expire_date'].astype(str), format='%Y%m%d')
    merged = merged[(merged['membership_expire_date'] > merged['date']) & 
      (merged['membership_expire_date'] <= pd.Timedelta(14, unit='D')+merged['date'])]
    
    if(i==0):
        result=merged
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
    else:
        result=result.append(merged)
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
        
    del(user_log_chunk)
    del(merged)

Loop  0 took 61.18744134902954 seconds
Loop  1 took 120.26592016220093 seconds
Loop  2 took 178.86283922195435 seconds
Loop  3 took 235.73748207092285 seconds
Loop  4 took 293.41613817214966 seconds
Loop  5 took 351.8942642211914 seconds
Loop  6 took 412.43714213371277 seconds
Loop  7 took 475.4400460720062 seconds
Loop  8 took 535.8442192077637 seconds
Loop  9 took 651.9518411159515 seconds

In [13]:
result.to_csv("Feb_user_log_14.csv")

# Jan 14 days

In [14]:
size=4e7 # 40 million
reader = pd.read_csv('user_logs.csv',chunksize=size,index_col=['msno'])
start_time = time.time()
for i in range(10):
    user_log_chunk=next(reader)
    
    
    user_log_chunk = user_log_chunk[(user_log_chunk.date<20170201)&(user_log_chunk.date>=20161201)]
    merged = pd.merge(user_log_chunk, Jan,left_index=True,right_index=True, how='inner')
    merged['date'] = pd.to_datetime(merged['date'].astype(str), format='%Y%m%d')
    merged['membership_expire_date'] = pd.to_datetime(merged['membership_expire_date'].astype(str), format='%Y%m%d')
    merged = merged[(merged['membership_expire_date'] > merged['date']) & 
      (merged['membership_expire_date'] <= pd.Timedelta(14, unit='D')+merged['date'])]
    
    if(i==0):
        result=merged
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
    else:
        result=result.append(merged)
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
        
    del(user_log_chunk)
    del(merged)

Loop  0 took 61.10034704208374 seconds
Loop  1 took 118.72557306289673 seconds
Loop  2 took 175.83149194717407 seconds
Loop  3 took 232.27944612503052 seconds
Loop  4 took 288.5788130760193 seconds
Loop  5 took 346.40627098083496 seconds
Loop  6 took 404.5621991157532 seconds
Loop  7 took 462.8406002521515 seconds
Loop  8 took 521.0772669315338 seconds
Loop  9 took 567.6219239234924 seconds

In [15]:
result.to_csv("Jan_user_log_14.csv")

# Feb 60 days

In [16]:
size=4e7 # 40 million
reader = pd.read_csv('user_logs.csv',chunksize=size,index_col=['msno'])
start_time = time.time()
for i in range(10):
    user_log_chunk=next(reader)
    
    
    user_log_chunk = user_log_chunk[(user_log_chunk.date<20170301)&(user_log_chunk.date>=20161201)]
    merged = pd.merge(user_log_chunk, Feb,left_index=True,right_index=True, how='inner')
    merged['date'] = pd.to_datetime(merged['date'].astype(str), format='%Y%m%d')
    merged['membership_expire_date'] = pd.to_datetime(merged['membership_expire_date'].astype(str), format='%Y%m%d')
    merged = merged[(merged['membership_expire_date'] > merged['date']) & 
      (merged['membership_expire_date'] <= pd.Timedelta(60, unit='D')+merged['date'])]
    
    if(i==0):
        result=merged
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
    else:
        result=result.append(merged)
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
        
    del(user_log_chunk)
    del(merged)

Loop  0 took 67.00481510162354 seconds
Loop  1 took 129.1377079486847 seconds
Loop  2 took 195.9444830417633 seconds
Loop  3 took 261.4244022369385 seconds
Loop  4 took 327.98682594299316 seconds
Loop  5 took 396.1724970340729 seconds
Loop  6 took 470.483745098114 seconds
Loop  7 took 546.5517070293427 seconds
Loop  8 took 623.2918441295624 seconds
Loop  9 took 688.6134161949158 seconds

In [17]:
result.to_csv("Feb_user_log_60.csv")

# Jan 60 days

In [18]:
size=4e7 # 40 million
reader = pd.read_csv('user_logs.csv',chunksize=size,index_col=['msno'])
start_time = time.time()
for i in range(10):
    user_log_chunk=next(reader)
    
    
    user_log_chunk = user_log_chunk[(user_log_chunk.date<20170201)&(user_log_chunk.date>=20161101)]
    merged = pd.merge(user_log_chunk, Jan,left_index=True,right_index=True, how='inner')
    merged['date'] = pd.to_datetime(merged['date'].astype(str), format='%Y%m%d')
    merged['membership_expire_date'] = pd.to_datetime(merged['membership_expire_date'].astype(str), format='%Y%m%d')
    merged = merged[(merged['membership_expire_date'] > merged['date']) & 
      (merged['membership_expire_date'] <= pd.Timedelta(60, unit='D')+merged['date'])]
    
    if(i==0):
        result=merged
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
    else:
        result=result.append(merged)
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
        
    del(user_log_chunk)
    del(merged)

Loop  0 took 71.55215692520142 seconds
Loop  1 took 139.50612092018127 seconds
Loop  2 took 206.02392196655273 seconds
Loop  3 took 272.2616488933563 seconds
Loop  4 took 341.14420199394226 seconds
Loop  5 took 412.9840409755707 seconds
Loop  6 took 484.6676070690155 seconds
Loop  7 took 563.362701177597 seconds
Loop  8 took 642.9122629165649 seconds
Loop  9 took 709.2284638881683 seconds

In [19]:
result.to_csv("Jan_user_log_60.csv")

# Total Feb

In [7]:
#writing as a function
def process_user_log(chunk):
    grouped_object=chunk.groupby(chunk.index,sort=False) # not sorting results in a minor speedup
    func = {'date':['max','count'], 
           'num_25':['sum'],'num_50':['sum'],
           'num_75':['sum'],'num_985':['sum'],
           'num_100':['sum'],'num_unq':['sum'],'total_secs':['sum'],'membership_expire_date':['min']}
    answer=grouped_object.agg(func)
    return answer

In [8]:
size=4e7 # 40 million
reader = pd.read_csv('user_logs.csv',chunksize=size,index_col=['msno'])
start_time = time.time()
for i in range(10):
    
    user_log_chunk=next(reader)
    merged = pd.merge(user_log_chunk, Feb,left_index=True,right_index=True, how='inner')
    merged = merged[merged['membership_expire_date'] > merged['date']]
    
    
    if(i==0):
        result=process_user_log(merged)
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
    else:
        result=result.append(process_user_log(merged))
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
    del(user_log_chunk)
    del(merged)

Loop  0 took 108.0434627532959 seconds
Loop  1 took 218.4573667049408 seconds
Loop  2 took 329.66002893447876 seconds
Loop  3 took 445.1568477153778 seconds
Loop  4 took 558.8026986122131 seconds
Loop  5 took 676.6149499416351 seconds
Loop  6 took 798.6362648010254 seconds
Loop  7 took 928.644633769989 seconds
Loop  8 took 1051.014518737793 seconds
Loop  9 took 1151.6992058753967 seconds

In [10]:
#result.columns.values
result.columns = ['date_max', 'date_count', 'num_25_sum', 'num_50_sum', 'num_75_sum',
       'num_985_sum', 'num_100_sum', 'num_unq_sum', 'total_secs_sum',
       'membership_expire_date']

In [19]:
func_2 = {'date_max':['max'],'date_count':['sum'] ,
           'num_25_sum':['sum'],'num_50_sum':['sum'],
           'num_75_sum':['sum'],'num_985_sum':['sum'],
           'num_100_sum':['sum'],'num_unq_sum':['sum'],'total_secs_sum':['sum'],'membership_expire_date':['min']}
Feb_total=result.groupby(result.index).agg(func_2)
Feb_total.columns = Feb_total.columns.get_level_values(0)
Feb_total

,date_max,date_count,num_25_sum,num_50_sum,num_75_sum,num_985_sum,num_100_sum,num_unq_sum,total_secs_sum,membership_expire_date
msno,,,,,,,,,,
+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=,20170214,89,520,263,258,459,1980,2453,6.409221e+05,20170215
+++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=,20170218,599,1382,485,414,548,15380,15080,4.012320e+06,20170219
+++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=,20170225,600,6657,2198,1463,1396,23749,24559,6.662899e+06,20170226
++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=,20170214,278,1396,432,342,457,4987,3780,1.454415e+06,20170215
++/UDNo9DLrxT8QVGiDi1OnWfczAdEwThaVyD0fXO50=,20170222,442,1076,533,299,415,4780,6599,1.392712e+06,20170223
...,...,...,...,...,...,...,...,...,...,...
zzx7wcys2Nha6yP2Skjs+R1/JNAfEuAWUaAp0qsV2Cg=,20170206,250,369,98,81,62,2367,2310,6.353585e+05,20170209
zzxPS8+wCuE4HE85EDp4WBHgS5l548vfwXJbQq1HZ9I=,20170209,665,2551,1115,647,801,63057,57588,1.594633e+07,20170210
zzxZeMFx2fjfKZigMnJa2w0EmloDbm8+8nTf/o/00GY=,20170225,482,2267,504,534,576,30470,25448,8.102517e+06,20170226
zzz1Dc3P9s53HAowRTrm3fNsWju5yeN4YBfNDq7Z99Q=,20170222,198,689,203,134,128,2332,2687,6.865855e+05,20170224
zzz4xr5LLzoxUqD6LfKiieCt8Or4dUWFQ0RA5gmkx8I=,20170127,220,1530,166,110,118,2540,3846,8.262096e+05,20170205

In [20]:
Feb_total['date_max'] = pd.to_datetime(Feb_total['date_max'].astype(str), format='%Y%m%d')
Feb_total['membership_expire_date'] = pd.to_datetime(Feb_total['membership_expire_date'].astype(str), format='%Y%m%d')
Feb_total['last_day']  = Feb_total['membership_expire_date'] - Feb_total['date_max']

In [23]:
Total = (Feb_total['num_25_sum']+Feb_total['num_50_sum']
         +Feb_total['num_75_sum']+Feb_total['num_985_sum']
         +Feb_total['num_100_sum'])

Feb_total['percentage_length'] = (Feb_total['num_25_sum']*0.25+Feb_total['num_50_sum']*0.5
                                          +Feb_total['num_75_sum']*0.75+Feb_total['num_985_sum']*0.985
                                          +Feb_total['num_100_sum'])/Total

Feb_total['percent_whole_song'] = (Feb_total['num_985_sum']+Feb_total['num_100_sum'])/Total
Feb_total['percent_lower25_song'] = Feb_total['num_25_sum']/Total
Feb_total['percent_unique'] = Feb_total['num_unq_sum']/Total

In [41]:
def process_user_log_2(chunk):
    grouped_object=chunk.groupby(chunk.index,sort=False) # not sorting results in a minor speedup
    func = {'date':'count', 
           'sec_dif_square':'sum'}
    answer=grouped_object.agg(func)
    return answer

In [49]:
#std
mean = pd.DataFrame(Feb_total['total_secs_sum']/Feb_total['date_count'])
mean.columns = ['mean_sec']
size=4e7 # 40 million
reader = pd.read_csv('user_logs.csv',chunksize=size,index_col=['msno'])
start_time = time.time()
for i in range(10):
    
    user_log_chunk=next(reader)
    merged = pd.merge(user_log_chunk, Feb,left_index=True,right_index=True, how='inner')
    merged = merged[merged['membership_expire_date'] > merged['date']]
    merged = pd.merge(merged,mean,left_index=True,right_on = 'msno',how = 'inner')
    merged['sec_dif_square'] = np.square(merged['total_secs']-merged['mean_sec'])
    
    if(i==0):
        result=process_user_log_2(merged)
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
    else:
        result=result.append(process_user_log_2(merged))
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
    del(user_log_chunk)
    del(merged)

Loop  0 took 145.10892295837402 seconds
Loop  1 took 278.149649143219 seconds
Loop  2 took 412.52634477615356 seconds
Loop  3 took 549.7896821498871 seconds
Loop  4 took 689.3902320861816 seconds
Loop  5 took 823.2976250648499 seconds
Loop  6 took 960.2775819301605 seconds
Loop  7 took 1097.2018642425537 seconds
Loop  8 took 1235.0456039905548 seconds
Loop  9 took 1346.1862120628357 seconds

In [53]:
std_sec = result.groupby('msno').agg({'date':'sum','sec_dif_square':'sum'})
std_sec = pd.DataFrame(std_sec.sec_dif_square/std_sec.date)
std_sec.columns = ['std_sec']

In [61]:
Feb_total = pd.merge(Feb_total,std_sec,left_index=True,right_index=True, how='inner')
Feb_total['last_day'] = Feb_total.last_day.dt.days.astype('int16')
Feb_total

,date_max,date_count,num_25_sum,num_50_sum,num_75_sum,num_985_sum,num_100_sum,num_unq_sum,total_secs_sum,membership_expire_date,last_day,percentage_length,percent_whole_song,percent_lower25_song,percent_unique,std_sec
msno,,,,,,,,,,,,,,,,
+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=,2017-02-14,89,520,263,258,459,1980,2453,6.409221e+05,2017-02-15,1 days,0.829631,0.700862,0.149425,0.704885,1.370140e+07
+++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=,2017-02-18,599,1382,485,414,548,15380,15080,4.012320e+06,2017-02-19,1 days,0.923625,0.874732,0.075897,0.828162,4.545468e+07
+++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=,2017-02-25,600,6657,2198,1463,1396,23749,24559,6.662899e+06,2017-02-26,1 days,0.817318,0.709049,0.187717,0.692525,1.144109e+08
++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=,2017-02-14,278,1396,432,342,457,4987,3780,1.454415e+06,2017-02-15,1 days,0.821992,0.714999,0.183346,0.496454,3.107733e+07
++/UDNo9DLrxT8QVGiDi1OnWfczAdEwThaVyD0fXO50=,2017-02-22,442,1076,533,299,415,4780,6599,1.392712e+06,2017-02-23,1 days,0.837467,0.731381,0.151485,0.929044,1.683024e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zzx7wcys2Nha6yP2Skjs+R1/JNAfEuAWUaAp0qsV2Cg=,2017-02-06,250,369,98,81,62,2367,2310,6.353585e+05,2017-02-09,3 days,0.883463,0.815922,0.123950,0.775949,5.149372e+06
zzxPS8+wCuE4HE85EDp4WBHgS5l548vfwXJbQq1HZ9I=,2017-02-09,665,2551,1115,647,801,63057,57588,1.594633e+07,2017-02-10,1 days,0.961208,0.936733,0.037421,0.844758,5.158133e+08
zzxZeMFx2fjfKZigMnJa2w0EmloDbm8+8nTf/o/00GY=,2017-02-25,482,2267,504,534,576,30470,25448,8.102517e+06,2017-02-26,1 days,0.939030,0.903787,0.065995,0.740823,1.768040e+08
zzz1Dc3P9s53HAowRTrm3fNsWju5yeN4YBfNDq7Z99Q=,2017-02-22,198,689,203,134,128,2332,2687,6.865855e+05,2017-02-24,2 days,0.812487,0.705680,0.197648,0.770797,1.052606e+07
zzz4xr5LLzoxUqD6LfKiieCt8Or4dUWFQ0RA5gmkx8I=,2017-01-27,220,1530,166,110,118,2540,3846,8.262096e+05,2017-02-05,9 days,0.717793,0.595430,0.342742,0.861559,1.013667e+07

In [82]:
Feb_total.to_csv("Feb_total.csv")

# Jan Total

In [72]:
#writing as a function
def process_user_log(chunk):
    grouped_object=chunk.groupby(chunk.index,sort=False) # not sorting results in a minor speedup
    func = {'date':['max','count'], 
           'num_25':['sum'],'num_50':['sum'],
           'num_75':['sum'],'num_985':['sum'],
           'num_100':['sum'],'num_unq':['sum'],'total_secs':['sum'],'membership_expire_date':['min']}
    answer=grouped_object.agg(func)
    return answer

In [73]:
size=4e7 # 40 million
reader = pd.read_csv('user_logs.csv',chunksize=size,index_col=['msno'])
start_time = time.time()
for i in range(10):
    
    user_log_chunk=next(reader)
    merged = pd.merge(user_log_chunk, Jan,left_index=True,right_index=True, how='inner')
    merged = merged[merged['membership_expire_date'] > merged['date']]
    
    
    if(i==0):
        result=process_user_log(merged)
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
    else:
        result=result.append(process_user_log(merged))
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
    del(user_log_chunk)
    del(merged)

Loop  0 took 127.24615597724915 seconds
Loop  1 took 248.4250249862671 seconds
Loop  2 took 370.47843623161316 seconds
Loop  3 took 492.0833249092102 seconds
Loop  4 took 612.9877650737762 seconds
Loop  5 took 737.1139430999756 seconds
Loop  6 took 863.9228138923645 seconds
Loop  7 took 993.4054839611053 seconds
Loop  8 took 1118.2740099430084 seconds
Loop  9 took 1228.7587032318115 seconds

In [74]:
#result.columns.values
result.columns = ['date_max', 'date_count', 'num_25_sum', 'num_50_sum', 'num_75_sum',
       'num_985_sum', 'num_100_sum', 'num_unq_sum', 'total_secs_sum',
       'membership_expire_date']

In [75]:
func_2 = {'date_max':['max'],'date_count':['sum'] ,
           'num_25_sum':['sum'],'num_50_sum':['sum'],
           'num_75_sum':['sum'],'num_985_sum':['sum'],
           'num_100_sum':['sum'],'num_unq_sum':['sum'],'total_secs_sum':['sum'],'membership_expire_date':['min']}
Jan_total=result.groupby(result.index).agg(func_2)
Jan_total.columns = Jan_total.columns.get_level_values(0)
Jan_total

,date_max,date_count,num_25_sum,num_50_sum,num_75_sum,num_985_sum,num_100_sum,num_unq_sum,total_secs_sum,membership_expire_date
msno,,,,,,,,,,
+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s=,20170103,584,710,234,209,173,57474,51833,1.419945e+07,20170104
+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=,20170113,59,377,186,178,294,1524,1765,4.715445e+05,20170115
+++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=,20170118,568,1317,465,390,526,14501,14259,3.787564e+06,20170119
+++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=,20170125,577,6468,2112,1417,1343,23339,23972,6.531657e+06,20170126
++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=,20170114,253,1308,397,319,425,4627,3599,1.346170e+06,20170115
...,...,...,...,...,...,...,...,...,...,...
zzxqpgPX1epGyR3SVRKb3XitWdt+JqDURxV5ea1D7Cg=,20170129,582,6878,1424,1036,1166,13284,17833,3.581878e+06,20170130
zzy7iqSpfcRq7R4hmKKuhI+CJRs79a6pteqEggpiNO0=,20170128,118,1801,417,343,428,3906,4829,1.074524e+06,20170129
zzyHq6TK2+cBkeGFUHvh12Z7UxFZiSM7dOOSllSBPDw=,20170109,473,1951,732,695,638,32136,26422,7.434506e+06,20170114
zzz1Dc3P9s53HAowRTrm3fNsWju5yeN4YBfNDq7Z99Q=,20170117,182,584,182,117,106,2179,2437,6.363762e+05,20170124
zzz4xr5LLzoxUqD6LfKiieCt8Or4dUWFQ0RA5gmkx8I=,20170121,219,1530,166,109,118,2539,3844,8.251265e+05,20170123

In [76]:
Jan_total['date_max'] = pd.to_datetime(Jan_total['date_max'].astype(str), format='%Y%m%d')
Jan_total['membership_expire_date'] = pd.to_datetime(Jan_total['membership_expire_date'].astype(str), format='%Y%m%d')
Jan_total['last_day']  = Jan_total['membership_expire_date'] - Jan_total['date_max']

In [77]:
Total = (Jan_total['num_25_sum']+Jan_total['num_50_sum']
         +Jan_total['num_75_sum']+Jan_total['num_985_sum']
         +Jan_total['num_100_sum'])

Jan_total['percentage_length'] = (Jan_total['num_25_sum']*0.25+Jan_total['num_50_sum']*0.5
                                          +Jan_total['num_75_sum']*0.75+Jan_total['num_985_sum']*0.985
                                          +Jan_total['num_100_sum'])/Total

Jan_total['percent_whole_song'] = (Jan_total['num_985_sum']+Jan_total['num_100_sum'])/Total
Jan_total['percent_lower25_song'] = Jan_total['num_25_sum']/Total
Jan_total['percent_unique'] = Jan_total['num_unq_sum']/Total

In [78]:
def process_user_log_2(chunk):
    grouped_object=chunk.groupby(chunk.index,sort=False) # not sorting results in a minor speedup
    func = {'date':'count', 
           'sec_dif_square':'sum'}
    answer=grouped_object.agg(func)
    return answer

In [79]:
#std
mean = pd.DataFrame(Jan_total['total_secs_sum']/Jan_total['date_count'])
mean.columns = ['mean_sec']
size=4e7 # 40 million
reader = pd.read_csv('user_logs.csv',chunksize=size,index_col=['msno'])
start_time = time.time()
for i in range(10):
    
    user_log_chunk=next(reader)
    merged = pd.merge(user_log_chunk, Jan,left_index=True,right_index=True, how='inner')
    merged = merged[merged['membership_expire_date'] > merged['date']]
    merged = pd.merge(merged,mean,left_index=True,right_on = 'msno',how = 'inner')
    merged['sec_dif_square'] = np.square(merged['total_secs']-merged['mean_sec'])
    
    if(i==0):
        result=process_user_log_2(merged)
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
    else:
        result=result.append(process_user_log_2(merged))
        print("Loop ",i,"took %s seconds" % (time.time() - start_time))
    del(user_log_chunk)
    del(merged)

Loop  0 took 143.89363718032837 seconds
Loop  1 took 275.43744111061096 seconds
Loop  2 took 409.99483704566956 seconds
Loop  3 took 550.4548110961914 seconds
Loop  4 took 696.3451220989227 seconds
Loop  5 took 846.386134147644 seconds
Loop  6 took 995.7160592079163 seconds
Loop  7 took 1147.0683121681213 seconds
Loop  8 took 1290.4344351291656 seconds
Loop  9 took 1404.1921861171722 seconds

In [80]:
std_sec = result.groupby('msno').agg({'date':'sum','sec_dif_square':'sum'})
std_sec = pd.DataFrame(std_sec.sec_dif_square/std_sec.date)
std_sec.columns = ['std_sec']

In [81]:
Jan_total = pd.merge(Jan_total,std_sec,left_index=True,right_index=True, how='inner')
Jan_total['last_day'] = Jan_total.last_day.dt.days.astype('int16')
Jan_total

,date_max,date_count,num_25_sum,num_50_sum,num_75_sum,num_985_sum,num_100_sum,num_unq_sum,total_secs_sum,membership_expire_date,last_day,percentage_length,percent_whole_song,percent_lower25_song,percent_unique,std_sec
msno,,,,,,,,,,,,,,,,
+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s=,2017-01-03,584,710,234,209,173,57474,51833,1.419945e+07,2017-01-04,1,0.988021,0.980391,0.012075,0.881514,1.701570e+08
+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=,2017-01-13,59,377,186,178,294,1524,1765,4.715445e+05,2017-01-15,2,0.834052,0.710434,0.147323,0.689723,1.400464e+07
+++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=,2017-01-18,568,1317,465,390,526,14501,14259,3.787564e+06,2017-01-19,1,0.922923,0.873714,0.076574,0.829060,4.480936e+07
+++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=,2017-01-25,577,6468,2112,1417,1343,23339,23972,6.531657e+06,2017-01-26,1,0.818870,0.711728,0.186511,0.691254,1.167588e+08
++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=,2017-01-14,253,1308,397,319,425,4627,3599,1.346170e+06,2017-01-15,1,0.821138,0.713963,0.184850,0.508621,3.301191e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zzxqpgPX1epGyR3SVRKb3XitWdt+JqDURxV5ea1D7Cg=,2017-01-29,582,6878,1424,1036,1166,13284,17833,3.581878e+06,2017-01-30,1,0.741593,0.607449,0.289137,0.749664,3.714916e+07
zzy7iqSpfcRq7R4hmKKuhI+CJRs79a6pteqEggpiNO0=,2017-01-28,118,1801,417,343,428,3906,4829,1.074524e+06,2017-01-29,1,0.760490,0.628571,0.261204,0.700363,4.339083e+07
zzyHq6TK2+cBkeGFUHvh12Z7UxFZiSM7dOOSllSBPDw=,2017-01-09,473,1951,732,695,638,32136,26422,7.434506e+06,2017-01-14,5,0.944330,0.906561,0.053967,0.730859,2.012147e+08
zzz1Dc3P9s53HAowRTrm3fNsWju5yeN4YBfNDq7Z99Q=,2017-01-17,182,584,182,117,106,2179,2437,6.363762e+05,2017-01-24,7,0.823283,0.721275,0.184343,0.769255,1.089261e+07
zzz4xr5LLzoxUqD6LfKiieCt8Or4dUWFQ0RA5gmkx8I=,2017-01-21,219,1530,166,109,118,2539,3844,8.251265e+05,2017-01-23,2,0.717723,0.595473,0.342896,0.861497,1.015020e+07

In [83]:
Jan_total.to_csv("Jan_total.csv")